### ISSUE TITLE
CSBC Staging DCA is down

### ISSUE THREAD

**Issue by ychae** [mc2-center/data_curator#13]
**Describe the bug**
Unable to access the [CSBC staging DCA](https://sagebio.shinyapps.io/csbc_data_curator_staging/)

**To Reproduce**
1. Go to [CSBC Staging DCA](https://sagebio.shinyapps.io/csbc_data_curator_staging/)
2. Get an error stating `Error : invalid_redirect_uri. Redirect URI https://sagebio.shinyapps.io/csbc_data_curator_staging is not registered for DCA (project-agnostic)`

**Expected behavior**
Should be able to log into CSBC DCA without the above error

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [X] Critical 🆘

**Screenshots**
<img width="890" alt="Screen Shot 2022-06-23 at 4 08 03 PM" src="https://user-images.githubusercontent.com/12868382/175429901-b8a06334-3993-480d-9f55-5fea269de6df.png">

**Desktop (if applicable, please complete the following information):**
- Chrome Version 101.0.4951.64 (Official Build) (x86_64)

**Comment by aclayton555** [comment]
I am receiving the same error.

**Comment by afwillia** [comment]
@ychae @aclayton555 it's fixed now. The problem came from [merging updates from the CSBC devel branch](https://github.com/Sage-Bionetworks/data_curator/commit/6925066fcd109a35d936414483f331061993978a) back into the main repo. [This workflow](https://github.com/Sage-Bionetworks/data_curator/actions/runs/2531902049/workflow) pushed the default DCA to the CSBC staging URL. To resolve it, I just reran the [most recent Action](https://github.com/mc2-center/data_curator/actions/runs/2531905421)
